apiVersion: v1
kind: Service
metadata:
  name: frontend-keycloak
spec:
  selector:
    app: frontend-keycloak
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30014
      targetPort: 80
  type: NodePort   
