apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-keycloak
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend-keycloak
  template:
    metadata:
      labels:
        app: backend-keycloak
    spec:
      containers:
      - name: backend-keycloak
        image: ghcr.io/ryunchang/springboot_crud_security_nonjwt:master
        imagePullPolicy: Always
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prd"
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
