apiVersion: v1	
kind: Service	
metadata:	
  name: backend-keycloak
  labels:
    app: backend-keycloak
spec:	
  ports:	
  - port: 80	
    targetPort: 8080
  selector:	
    app: backend-keycloak
  type: ClusterIP
